export const ALBUM_LAYOUTS = {
  full: {
    id: 'full',
    name: '全幅',
    icon: '▭',
    description: '单张大图铺满整页',
    maxPhotos: 1,
    gridAreas: '"p0"',
    gridRows: '1fr',
    gridColumns: '1fr',
  },
  duo: {
    id: 'duo',
    name: '双图',
    icon: '◫◫',
    description: '左右两张并排',
    maxPhotos: 2,
    gridAreas: '"p0 p1"',
    gridRows: '1fr',
    gridColumns: '1fr 1fr',
    gap: 'md',
  },
  trio: {
    id: 'trio',
    name: '三图',
    icon: '⊞',
    description: '一横两竖组合',
    maxPhotos: 3,
    gridAreas: '"p0 p0" "p1 p2"',
    gridRows: '1.4fr 1fr',
    gridColumns: '1fr 1fr',
    gap: 'md',
  },
  grid4: {
    id: 'grid4',
    name: '四宫格',
    icon: '▦',
    description: '2×2 均衡排布',
    maxPhotos: 4,
    gridAreas: '"p0 p1" "p2 p3"',
    gridRows: '1fr 1fr',
    gridColumns: '1fr 1fr',
    gap: 'md',
  },
  'img-left-text': {
    id: 'img-left-text',
    name: '左图右文',
    icon: '▥',
    description: '左图右侧配文区',
    maxPhotos: 1,
    textArea: true,
    gridAreas: '"p0 t"',
    gridRows: '1fr',
    gridColumns: '1.5fr 1fr',
  },
  'img-right-text': {
    id: 'img-right-text',
    name: '右图左文',
    icon: '▤',
    description: '右图左侧配文区',
    maxPhotos: 1,
    textArea: true,
    gridAreas: '"t p0"',
    gridRows: '1fr',
    gridColumns: '1fr 1.5fr',
  },
  'hero-text': {
    id: 'hero-text',
    name: '题图页',
    icon: '▬',
    description: '通栏题图 + 下方大字配文',
    maxPhotos: 1,
    heroText: true,
    gridAreas: '"p0" "t"',
    gridRows: '1.7fr 1fr',
    gridColumns: '1fr',
  },
  strip: {
    id: 'strip',
    name: '胶片条',
    icon: '▤▤▤',
    description: '横向胶片带，最多五张',
    maxPhotos: 5,
    strip: true,
    gridAreas: '"p0 p1 p2 p3 p4"',
    gridRows: '1fr',
    gridColumns: 'repeat(5, 1fr)',
    gap: 'sm',
  },
};

export function getLayout(layoutId) {
  return ALBUM_LAYOUTS[layoutId] || ALBUM_LAYOUTS.full;
}

export function getLayoutOptions() {
  return Object.values(ALBUM_LAYOUTS).map(({ id, name, icon, description }) => ({
    id,
    name,
    icon,
    description,
  }));
}
