-- forum_weekly_checkins 表 - 论坛周签到记录

CREATE TABLE IF NOT EXISTS public.forum_weekly_checkins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  week_start_date date NOT NULL,
  signed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT forum_weekly_checkins_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON DELETE CASCADE,
  CONSTRAINT forum_weekly_checkins_user_week_key UNIQUE (user_id, week_start_date)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_forum_weekly_checkins_user_signed_at
  ON public.forum_weekly_checkins USING btree (user_id, signed_at DESC) TABLESPACE pg_default;
