export const routeCatalog = {
  Home: { category: '公共入口', title: '首页', description: '网站首屏入口，承载方块之家核心导航、精选内容和主要业务入口。' },
  Shop: { category: '商业与周边', title: '周边商城', description: '周边商品展示与购买相关入口，连接产品数据、购物体验和商品详情。' },
  Gift: { category: '商业与周边', title: '礼物档案', description: '礼物、纪念品或活动赠品的展示页面。' },
  Login: { category: '账号系统', title: '登录', description: '用户登录与注册相关入口，为我的方块、论坛和后台能力提供身份基础。' },
  ResetPassword: { category: '账号系统', title: '重置密码', description: '账号密码找回与重置流程页面。' },
  MBTI: { category: '互动工具', title: 'MBTI 测评', description: '性格测评互动页面，包含题目、计分和结果展示。' },
  Birthday: { category: '活动专题', title: '生日专题', description: '生日活动或庆祝专题页，用于承载阶段性运营内容。' },
  About: { category: '公共入口', title: '关于我们', description: '介绍方块之家、团队背景和项目定位的品牌说明页。' },
  Join: { category: '公共入口', title: '加入我们', description: '招募、加入社区或团队协作相关入口。' },
  Download: { category: '公共入口', title: '下载', description: '客户端、资源包或相关文件下载入口。' },
  Tutorial: { category: '公共入口', title: '教程', description: '面向用户的使用教程、安装说明和上手文档入口。' },
  Shows: { category: '社区内容', title: '节目', description: '节目、视频栏目或内容系列的聚合展示页面。' },
  CharacterBook: { category: '社区内容', title: '设定集', description: '角色、世界观或项目设定资料页面。' },
  AiChat: { category: 'AI 功能', title: 'BOH AI 对话', description: 'AI 聊天主入口，连接对话、上下文和内容安全能力。' },
  AiPlaza: { category: 'AI 功能', title: 'AI 广场', description: 'AI 角色、智能体或公开 AI 内容的广场入口。' },
  BOH8YearsEvent: { category: '活动专题', title: '八周年活动', description: '八周年活动主页面，聚合活动内容、视觉物料和参与入口。' },
  LithiumIron: { category: '活动专题', title: '锂铁专题', description: '锂铁主题专题页面，承载单独项目或活动内容。' },
  Newsroom: { category: '社区内容', title: '新闻', description: '新闻公告列表页，展示站内更新、活动通知和重要发布。' },
  Activities: { category: '社区内容', title: '活动容器', description: '活动模块的父级入口，默认导向活动列表，并承载子路由视图。' },
  ActivitiesPhotoWall: { category: '社区内容', title: '活动照片墙', description: '活动图片墙子页面，用于展示活动照片与影像记录。' },
  ActivitiesList: { category: '社区内容', title: '活动列表', description: '活动列表子页面，用于浏览当前和历史活动。' },
  Forum: { category: '社区内容', title: '论坛', description: '社区论坛首页，承载帖子列表、发帖入口和内容筛选。' },
  CommunityLotteries: { category: '社区内容', title: '社区抽奖', description: '展示当前进行中的社区抽奖和历史开奖结果。' },
  PostDetail: { category: '社区内容', title: '帖子详情', description: '论坛帖子详情页，通过动态 id 加载单篇帖子、回复和互动。' },
  UserProfile: { category: '社区内容', title: '用户主页', description: '公开用户资料页，通过 username 参数展示用户信息与内容。' },
  Subscriptions: { category: '用户空间', title: '订阅', description: '订阅权益、会员状态或付费能力相关页面。' },
  Address: { category: '用户空间', title: '地址管理', description: '用户收货地址管理入口。' },
  Messages: { category: '用户空间', title: '消息中心', description: '用户消息、回复提醒和系统通知聚合页。' },
  Partners: { category: '用户空间', title: '伙伴管理', description: '用户伙伴、关系或协作名单相关页面。' },
  UserSpace: { category: '用户空间', title: '我的方块', description: '新版用户中心主入口，聚合资料、内容、笔记和账号管理。' },
  AccountSecurity: { category: '用户空间', title: '账号安全', description: '账号安全、密码和设备信任管理入口。' },
  BOHCloudPlus: { category: '用户空间', title: 'BOH Cloud+ 笔记', description: '用户云笔记和树洞内容管理入口。' },
  SharedMemoryManagement: { category: '用户空间', title: '共享记忆管理', description: '用户共享记忆内容管理入口。' },
  TagsImpressions: { category: '用户空间', title: '标签印象', description: '用户标签、印象或画像信息管理页面。' },
  PushplusSettings: { category: '用户空间', title: 'PushPlus 设置', description: '用户订阅通知与 PushPlus 推送配置入口。' },
  UserCenterIndex: { category: '用户空间', title: '用户中心索引', description: '旧用户中心索引页，作为个人相关页面的过渡入口。' },
  GlobalPagesIndex: { category: '工程维护', title: '全站 Vue 入口说明', description: '当前这个页面，用于梳理项目里所有路由入口和视图文件。' },
  CreatorStudio: { category: '创作工具', title: '创作工作台', description: '废弃编辑器已下线，当前仅保留占位入口。' },
  DataManagement: { category: '后台管理', title: '数据管理', description: '管理员数据管理页面，需要后台权限访问。' },
  AlertStyleEditor: { category: '后台管理', title: '弹窗样式编辑器', description: '管理员调试或编辑全局弹窗样式的后台工具。' }
};

export const redirectCatalog = {
  '/activities': '活动页父级入口，默认展示活动列表。',
  '/mailbox': '旧站内信入口，兼容跳转到 /user-space/messages 邮件标签。',
  '/user-center/points': '旧积分入口，兼容跳转到 /user-space/subscriptions。'
};

export const routeComponentPaths = {
  Home: 'src/views/Home/index.vue',
  Shop: 'src/views/Shop/index.vue',
  Gift: 'src/views/Gift/index.vue',
  Login: 'src/views/Login/index.vue',
  ResetPassword: 'src/views/ResetPassword/index.vue',
  MBTI: 'src/views/MBTI/index.vue',
  Birthday: 'src/views/Birthday/index.vue',
  About: 'src/views/AboutUs/index.vue',
  Join: 'src/views/Join/index.vue',
  Download: 'src/views/Download/index.vue',
  Tutorial: 'src/views/Tutorial/index.vue',
  Shows: 'src/views/Shows/index.vue',
  CharacterBook: 'src/views/CharacterBook/index.vue',
  AiChat: 'src/views/BOHAI/BOHAI/index.vue',
  AiPlaza: 'src/views/AIPlaza/index.vue',
  BOH8YearsEvent: 'src/views/BOH8YearsEvent/index.vue',
  LithiumIron: 'src/views/LithiumIron/index.vue',
  Newsroom: 'src/views/Newsroom/index.vue',
  Activities: 'src/views/activities/index.vue',
  ActivitiesPhotoWall: 'src/views/activities/ActivitiesPhotoWall.vue',
  ActivitiesList: 'src/views/activities/ActivitiesList.vue',
  Forum: 'src/views/Forum/index.vue',
  CommunityLotteries: 'src/views/CommunityLotteries/index.vue',
  PostDetail: 'src/views/PostDetail/index.vue',
  UserProfile: 'src/views/Profile/index.vue',
  Subscriptions: 'src/views/user-center/Subscription/index.vue',
  Address: 'src/views/user-center/Address/index.vue',
  Messages: 'src/views/user-center/Messages/index.vue',
  Partners: 'src/views/user-center/Partners.vue',
  UserSpace: 'src/views/user-center/UserSpace/index.vue',
  AccountSecurity: 'src/views/user-center/AccountSecurity/index.vue',
  BOHCloudPlus: 'src/views/user-center/Cloud+/index.vue',
  SharedMemoryManagement: 'src/views/user-center/SharedMemoryManagement.vue',
  TagsImpressions: 'src/views/user-center/TagsImpressions.vue',
  PushplusSettings: 'src/views/user-center/PushplusSettingsPage.vue',
  UserCenterIndex: 'src/views/user-center/UserCenterIndex.vue',
  GlobalPagesIndex: 'src/views/GlobalPagesIndex/index.vue',
  CreatorStudio: 'src/views/user-center/CreateStudio/index.vue',
  DataManagement: 'src/views/DataManagement/index.vue',
  AlertStyleEditor: 'src/views/AlertStyleEditor/index.vue'
};
