-- 用户关注关系表 (user_follows)
-- 实现关注/粉丝功能：用户之间的一对多关注关系
--
-- Down Migration (回滚):
--   DROP TRIGGER IF EXISTS trg_prevent_self_follow ON public.user_follows;
--   DROP FUNCTION IF EXISTS prevent_self_follow();
--   DROP INDEX IF EXISTS idx_user_follows_following;
--   DROP INDEX IF EXISTS idx_user_follows_follower;
--   DROP TABLE IF EXISTS public.user_follows;

CREATE TABLE IF NOT EXISTS public.user_follows (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    following_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT unique_follow UNIQUE (follower_id, following_id)
);

-- 索引：快速查某人的粉丝（谁关注了 TA）
CREATE INDEX IF NOT EXISTS idx_user_follows_following
    ON public.user_follows USING btree (following_id, created_at DESC);

-- 索引：快速查某人关注了谁
CREATE INDEX IF NOT EXISTS idx_user_follows_follower
    ON public.user_follows USING btree (follower_id, created_at DESC);

-- 禁止关注自己的约束（数据库级确保）
CREATE OR REPLACE FUNCTION prevent_self_follow()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.follower_id = NEW.following_id THEN
        RAISE EXCEPTION '不能关注自己'
            USING HINT = 'follower_id 和 following_id 不能相同';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS trg_prevent_self_follow ON public.user_follows;
CREATE TRIGGER trg_prevent_self_follow
    BEFORE INSERT OR UPDATE ON public.user_follows
    FOR EACH ROW EXECUTE FUNCTION prevent_self_follow();

-- RLS 策略
ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;

-- 查看关注关系需尊重隐私设置
DROP POLICY IF EXISTS "任何人都可查看关注关系" ON public.user_follows;
DROP POLICY IF EXISTS "查看关注关系需尊重隐私设置" ON public.user_follows;
CREATE POLICY "查看关注关系需尊重隐私设置"
    ON public.user_follows FOR SELECT
    USING (
        follower_id = auth.uid()
        OR following_id = auth.uid()
        OR (
            auth.uid() IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 FROM public.profiles p
                WHERE p.id = user_follows.following_id AND p.hide_follow_data = true
            )
            AND NOT EXISTS (
                SELECT 1 FROM public.profiles p
                WHERE p.id = user_follows.follower_id AND p.hide_follow_data = true
            )
        )
    );

-- 用户只能插入自己的关注（follower_id 必须是自己）
DROP POLICY IF EXISTS "用户可关注他人" ON public.user_follows;
CREATE POLICY "用户可关注他人"
    ON public.user_follows FOR INSERT
    WITH CHECK (auth.uid() = follower_id);

-- 用户只能删除自己的关注
DROP POLICY IF EXISTS "用户可取消关注" ON public.user_follows;
CREATE POLICY "用户可取消关注"
    ON public.user_follows FOR DELETE
    USING (auth.uid() = follower_id);

-- 禁止更新关注关系
DROP POLICY IF EXISTS "禁止更新关注关系" ON public.user_follows;
CREATE POLICY "禁止更新关注关系"
    ON public.user_follows FOR UPDATE
    USING (false) WITH CHECK (false);

-- 显式 GRANT/REVOKE（先 REVOKE ALL 确保 Supabase 自动授权不残留）
REVOKE ALL ON public.user_follows FROM anon;
REVOKE ALL ON public.user_follows FROM authenticated;
GRANT SELECT, INSERT, DELETE ON public.user_follows TO authenticated;

COMMENT ON TABLE public.user_follows IS '用户关注关系表';
COMMENT ON COLUMN public.user_follows.follower_id IS '关注者（主动关注的人）';
COMMENT ON COLUMN public.user_follows.following_id IS '被关注者';
COMMENT ON COLUMN public.user_follows.created_at IS '关注时间';
