-- 登录验证码信任窗口：
-- 1) 老用户在已信任设备上可在 30 天内免验证码登录（滑动续期）
-- 2) 新设备/信任过期/近期失败过多时，仍要求验证码

begin;

create table if not exists public.auth_trusted_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  device_id_hash text not null,
  trusted_since timestamp with time zone not null default now(),
  trust_until timestamp with time zone not null,
  last_login_at timestamp with time zone not null default now(),
  last_used_captcha boolean not null default false,
  last_user_agent text null,
  revoked_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint auth_trusted_devices_device_hash_len
    check (char_length(trim(device_id_hash)) between 32 and 128)
);

create unique index if not exists uq_auth_trusted_devices_user_device
  on public.auth_trusted_devices (user_id, device_id_hash);

create index if not exists idx_auth_trusted_devices_user_trust_until
  on public.auth_trusted_devices (user_id, trust_until desc);

create table if not exists public.auth_login_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references public.profiles (id) on delete set null,
  login_key text not null default '',
  device_id_hash text not null default '',
  succeeded boolean not null default false,
  used_captcha boolean not null default false,
  failure_code text null,
  user_agent text null,
  created_at timestamp with time zone not null default now(),
  constraint auth_login_events_login_key_len
    check (char_length(trim(login_key)) between 1 and 190),
  constraint auth_login_events_device_hash_len
    check (char_length(trim(device_id_hash)) between 1 and 128),
  constraint auth_login_events_failure_code_len
    check (failure_code is null or char_length(trim(failure_code)) between 1 and 80)
);

create index if not exists idx_auth_login_events_login_device_created
  on public.auth_login_events (login_key, device_id_hash, created_at desc);

create index if not exists idx_auth_login_events_user_created
  on public.auth_login_events (user_id, created_at desc);

alter table public.auth_trusted_devices enable row level security;
alter table public.auth_login_events enable row level security;

drop policy if exists auth_trusted_devices_select_own on public.auth_trusted_devices;
create policy auth_trusted_devices_select_own
  on public.auth_trusted_devices
  for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.touch_auth_trusted_devices_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_auth_trusted_devices_updated_at on public.auth_trusted_devices;
create trigger trg_auth_trusted_devices_updated_at
before update on public.auth_trusted_devices
for each row
execute function public.touch_auth_trusted_devices_updated_at();

create or replace function public.should_require_login_captcha(
  p_login_id text,
  p_device_id_hash text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_login_key text := lower(trim(coalesce(p_login_id, '')));
  v_device_hash text := trim(coalesce(p_device_id_hash, ''));
  v_user_id uuid := null;
  v_join_date date := null;
  v_is_old_user boolean := false;
  v_trust_until timestamp with time zone := null;
  v_recent_failed integer := 0;
begin
  if v_login_key = '' or v_device_hash = '' then
    return jsonb_build_object(
      'ok', true,
      'require_captcha', true,
      'reason', 'INVALID_INPUT'
    );
  end if;

  if position('@' in v_login_key) > 0 then
    select p.id, p.join_date
      into v_user_id, v_join_date
      from public.profiles p
     where lower(coalesce(p.email, '')) = v_login_key
     limit 1;
  else
    select p.id, p.join_date
      into v_user_id, v_join_date
      from public.profiles p
     where lower(coalesce(p.username, '')) = v_login_key
     limit 1;
  end if;

  if v_user_id is null then
    return jsonb_build_object(
      'ok', true,
      'require_captcha', true,
      'reason', 'UNKNOWN_ACCOUNT'
    );
  end if;

  v_is_old_user := coalesce(v_join_date <= (current_date - 30), false);
  if not v_is_old_user then
    return jsonb_build_object(
      'ok', true,
      'require_captcha', true,
      'reason', 'ACCOUNT_TOO_NEW'
    );
  end if;

  select count(*)
    into v_recent_failed
    from public.auth_login_events e
   where e.login_key = v_login_key
     and e.device_id_hash = v_device_hash
     and e.succeeded = false
     and e.created_at >= (now() - interval '15 minutes');

  if v_recent_failed >= 3 then
    return jsonb_build_object(
      'ok', true,
      'require_captcha', true,
      'reason', 'RECENT_FAILURES',
      'recent_failed', v_recent_failed
    );
  end if;

  select d.trust_until
    into v_trust_until
    from public.auth_trusted_devices d
   where d.user_id = v_user_id
     and d.device_id_hash = v_device_hash
     and d.revoked_at is null
   order by d.trust_until desc
   limit 1;

  if v_trust_until is not null and v_trust_until > now() then
    return jsonb_build_object(
      'ok', true,
      'require_captcha', false,
      'reason', 'TRUSTED_DEVICE',
      'trust_until', v_trust_until
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'require_captcha', true,
    'reason', 'CAPTCHA_REQUIRED'
  );
exception
  when others then
    return jsonb_build_object(
      'ok', false,
      'require_captcha', true,
      'reason', 'CHECK_FAILED',
      'message', coalesce(sqlerrm, 'UNKNOWN_ERROR')
    );
end;
$$;

create or replace function public.record_login_attempt(
  p_login_id text,
  p_device_id_hash text,
  p_succeeded boolean,
  p_used_captcha boolean default false,
  p_failure_code text default null,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_login_key text := lower(trim(coalesce(p_login_id, '')));
  v_device_hash text := trim(coalesce(p_device_id_hash, ''));
  v_failure_code text := nullif(left(trim(coalesce(p_failure_code, '')), 80), '');
  v_user_agent text := nullif(left(trim(coalesce(p_user_agent, '')), 512), '');
  v_user_id uuid := auth.uid();
  v_join_date date := null;
  v_is_old_user boolean := false;
  v_existing_trust_until timestamp with time zone := null;
  v_new_trust_until timestamp with time zone := null;
begin
  if v_login_key = '' or v_device_hash = '' then
    return jsonb_build_object(
      'ok', false,
      'message', 'INVALID_INPUT'
    );
  end if;

  insert into public.auth_login_events (
    user_id,
    login_key,
    device_id_hash,
    succeeded,
    used_captcha,
    failure_code,
    user_agent
  ) values (
    v_user_id,
    v_login_key,
    v_device_hash,
    coalesce(p_succeeded, false),
    coalesce(p_used_captcha, false),
    v_failure_code,
    v_user_agent
  );

  if coalesce(p_succeeded, false) and v_user_id is not null then
    select p.join_date
      into v_join_date
      from public.profiles p
     where p.id = v_user_id;

    v_is_old_user := coalesce(v_join_date <= (current_date - 30), false);

    if v_is_old_user then
      select d.trust_until
        into v_existing_trust_until
        from public.auth_trusted_devices d
       where d.user_id = v_user_id
         and d.device_id_hash = v_device_hash
         and d.revoked_at is null
       order by d.trust_until desc
       limit 1;

      if coalesce(p_used_captcha, false)
         or (v_existing_trust_until is not null and v_existing_trust_until > now()) then
        v_new_trust_until := now() + interval '30 days';

        insert into public.auth_trusted_devices (
          user_id,
          device_id_hash,
          trusted_since,
          trust_until,
          last_login_at,
          last_used_captcha,
          last_user_agent,
          revoked_at
        ) values (
          v_user_id,
          v_device_hash,
          now(),
          v_new_trust_until,
          now(),
          coalesce(p_used_captcha, false),
          v_user_agent,
          null
        )
        on conflict (user_id, device_id_hash)
        do update
          set trusted_since = case
            when public.auth_trusted_devices.revoked_at is null
              then public.auth_trusted_devices.trusted_since
            else excluded.trusted_since
          end,
          trust_until = excluded.trust_until,
          last_login_at = excluded.last_login_at,
          last_used_captcha = excluded.last_used_captcha,
          last_user_agent = excluded.last_user_agent,
          revoked_at = null;
      end if;
    end if;
  end if;

  return jsonb_build_object(
    'ok', true,
    'trusted_until', v_new_trust_until
  );
exception
  when others then
    return jsonb_build_object(
      'ok', false,
      'message', coalesce(sqlerrm, 'UNKNOWN_ERROR')
    );
end;
$$;

revoke all on function public.should_require_login_captcha(text, text, text) from public;
revoke all on function public.record_login_attempt(text, text, boolean, boolean, text, text) from public;

grant execute on function public.should_require_login_captcha(text, text, text) to anon;
grant execute on function public.should_require_login_captcha(text, text, text) to authenticated;
grant execute on function public.should_require_login_captcha(text, text, text) to service_role;

grant execute on function public.record_login_attempt(text, text, boolean, boolean, text, text) to anon;
grant execute on function public.record_login_attempt(text, text, boolean, boolean, text, text) to authenticated;
grant execute on function public.record_login_attempt(text, text, boolean, boolean, text, text) to service_role;

grant all on table public.auth_trusted_devices to service_role;
grant all on table public.auth_login_events to service_role;

commit;
