begin;

-- =============================================
-- 发帖有奖活动（可配置运营活动）
-- 1) 活动规则表 post_reward_campaigns
-- 2) 领取记录表 post_reward_claims（幂等 + 计上限）
-- 3) 发放 RPC grant_post_publish_reward(p_post_id)
-- 4) 查询 RPC get_active_post_reward()
-- 管理面板在 operations 模块 CRUD 活动；发帖成功时由前端调用发放 RPC。
-- =============================================

-- ---------- 1. 活动规则表 ----------
create table if not exists public.post_reward_campaigns (
  id bigint generated by default as identity primary key,
  title text not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  points_per_post integer not null default 0,   -- 每帖奖励积分
  daily_limit integer not null default 0,        -- 每人每日上限（0 = 不限）
  monthly_limit integer not null default 0,      -- 每人每月上限（0 = 不限）
  status text not null default 'active',         -- active / inactive
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 便于“当前进行中活动”快速查询
create index if not exists idx_post_reward_campaigns_active
  on public.post_reward_campaigns (status, start_at, end_at);

alter table public.post_reward_campaigns enable row level security;

-- 管理员全权读写
drop policy if exists post_reward_campaigns_admin_all on public.post_reward_campaigns;
create policy post_reward_campaigns_admin_all on public.post_reward_campaigns
  for all to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());

-- 登录用户可读（活动是公开运营信息；精确“进行中”判断仍走 RPC）
drop policy if exists post_reward_campaigns_authenticated_select on public.post_reward_campaigns;
create policy post_reward_campaigns_authenticated_select on public.post_reward_campaigns
  for select to authenticated
  using (true);

grant select, insert, update, delete on table public.post_reward_campaigns to authenticated;
grant all on table public.post_reward_campaigns to service_role;

-- ---------- 2. 领取记录表 ----------
create table if not exists public.post_reward_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  post_id uuid not null references public.posts (id) on delete cascade,
  campaign_id bigint not null references public.post_reward_campaigns (id) on delete cascade,
  points_awarded integer not null default 0,
  created_at timestamptz not null default now()
);

-- 同一帖只领一次（幂等防重复/防网络重试）
create unique index if not exists uq_post_reward_claims_user_post
  on public.post_reward_claims (user_id, post_id);

-- 按活动 + 用户 + 时间计每日/每月已领，支撑上限校验
create index if not exists idx_post_reward_claims_campaign_user_time
  on public.post_reward_claims (campaign_id, user_id, created_at);

alter table public.post_reward_claims enable row level security;

drop policy if exists post_reward_claims_admin_all on public.post_reward_claims;
create policy post_reward_claims_admin_all on public.post_reward_claims
  for all to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());

drop policy if exists post_reward_claims_owner_select on public.post_reward_claims;
create policy post_reward_claims_owner_select on public.post_reward_claims
  for select to authenticated
  using (user_id = auth.uid());

grant select, insert, update, delete on table public.post_reward_claims to authenticated;
grant all on table public.post_reward_claims to service_role;

-- ---------- 3. 发放 RPC ----------
create or replace function public.grant_post_publish_reward(p_post_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_post_author uuid;
  v_campaign record;
  v_now timestamptz := now();
  v_today_start timestamptz := date_trunc('day', timezone('Asia/Shanghai', v_now));
  v_month_start timestamptz := date_trunc('month', timezone('Asia/Shanghai', v_now));
  v_awarded integer := 0;
  v_current_points integer := 0;
  v_row_count bigint;
begin
  if v_user_id is null then
    return jsonb_build_object('ok', false, 'message', 'NOT_AUTHENTICATED');
  end if;

  -- 校验帖子存在且归属当前用户
  select author_id into v_post_author from public.posts where id = p_post_id;
  if v_post_author is null or v_post_author <> v_user_id then
    return jsonb_build_object('ok', false, 'message', 'POST_NOT_FOUND_OR_FORBIDDEN');
  end if;

  -- 查找“当前进行中”的活动（时间窗内且启用），取最近创建的一条
  select * into v_campaign
  from public.post_reward_campaigns
  where status = 'active'
    and start_at <= v_now
    and end_at >= v_now
  order by start_at desc
  limit 1;

  if v_campaign.id is null then
    return jsonb_build_object('ok', true, 'awarded', 0, 'message', 'NO_ACTIVE_CAMPAIGN');
  end if;

  -- 写入领取记录（同一帖幂等，不重复发）。先以 0 占位，通过上限校验后再回填。
  insert into public.post_reward_claims (user_id, post_id, campaign_id, points_awarded)
  values (v_user_id, p_post_id, v_campaign.id, 0)
  on conflict (user_id, post_id) do nothing;
  get diagnostics v_row_count = row_count;

  if v_row_count = 0 then
    -- 该帖已领过（网络重试等），直接返回，不重复发
    return jsonb_build_object('ok', true, 'awarded', 0, 'already_claimed', true, 'message', 'ALREADY_CLAIMED');
  end if;

  -- 每月上限校验（用当月已发放总额）
  -- 注：并发发帖在临界值附近可能多发放一个帖的积分（非资金场景，影响可忽略）。
  select coalesce(sum(c.points_awarded), 0) into v_awarded
  from public.post_reward_claims c
  where c.campaign_id = v_campaign.id
    and c.user_id = v_user_id
    and c.created_at >= v_month_start;

  if (v_campaign.monthly_limit is not null and v_campaign.monthly_limit > 0
      and v_awarded + v_campaign.points_per_post > v_campaign.monthly_limit) then
    delete from public.post_reward_claims where user_id = v_user_id and post_id = p_post_id;
    return jsonb_build_object('ok', true, 'awarded', 0, 'skipped', true, 'reason', 'MONTHLY_LIMIT', 'message', 'MONTHLY_LIMIT_REACHED');
  end if;

  -- 每日上限校验（用当日已发放总额）
  select coalesce(sum(c.points_awarded), 0) into v_awarded
  from public.post_reward_claims c
  where c.campaign_id = v_campaign.id
    and c.user_id = v_user_id
    and c.created_at >= v_today_start;

  if (v_campaign.daily_limit is not null and v_campaign.daily_limit > 0
      and v_awarded + v_campaign.points_per_post > v_campaign.daily_limit) then
    delete from public.post_reward_claims where user_id = v_user_id and post_id = p_post_id;
    return jsonb_build_object('ok', true, 'awarded', 0, 'skipped', true, 'reason', 'DAILY_LIMIT', 'message', 'DAILY_LIMIT_REACHED');
  end if;

  -- 发放积分 + 写流水（reason='forum_post'，补齐签到不写流水的缺口）
  v_awarded := v_campaign.points_per_post;
  update public.profiles set points = coalesce(points, 0) + v_awarded where id = v_user_id;
  update public.post_reward_claims set points_awarded = v_awarded where user_id = v_user_id and post_id = p_post_id;

  insert into public.points_transactions (user_id, amount, balance_after, reason, remark)
  values (
    v_user_id,
    v_awarded,
    (select points from public.profiles where id = v_user_id),
    'forum_post',
    '发帖有奖：' || coalesce(v_campaign.title, '')
  );

  select coalesce(points, 0) into v_current_points from public.profiles where id = v_user_id;

  return jsonb_build_object(
    'ok', true,
    'awarded', v_awarded,
    'current_points', v_current_points,
    'campaign_id', v_campaign.id,
    'campaign_title', v_campaign.title,
    'message', 'REWARDED'
  );
end;
$$;

revoke all on function public.grant_post_publish_reward(uuid) from public;
grant execute on function public.grant_post_publish_reward(uuid) to authenticated;
grant execute on function public.grant_post_publish_reward(uuid) to service_role;

-- ---------- 4. 查询当前进行中活动（供论坛横幅展示） ----------
create or replace function public.get_active_post_reward()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  select jsonb_build_object(
    'id', c.id,
    'title', c.title,
    'pointsPerPost', c.points_per_post,
    'endAt', c.end_at
  ) into v_result
  from public.post_reward_campaigns c
  where c.status = 'active'
    and c.start_at <= now()
    and c.end_at >= now()
  order by c.start_at desc
  limit 1;
  return v_result; -- 无活动返回 null
end;
$$;

revoke all on function public.get_active_post_reward() from public;
grant execute on function public.get_active_post_reward() to authenticated;
grant execute on function public.get_active_post_reward() to service_role;

commit;
