-- ============================================
-- AI 配额系统: 使用记录表 + 配置表
-- 北京时区 (UTC+8) 按自然日 0 点重置
-- ============================================

-- 1. AI 使用记录
create table if not exists public.ai_quota_log (
  id          bigint generated by default as identity primary key,
  user_id     uuid references public.profiles(id) on delete set null,
  ip_address  text,
  model       text not null,
  mode        text not null,
  created_at  timestamptz not null default now()
);

create index if not exists idx_ai_quota_user_date
  on public.ai_quota_log(user_id, created_at);
create index if not exists idx_ai_quota_ip_date
  on public.ai_quota_log(ip_address, created_at);

-- 2. 配额配置（管理面板可调）
create table if not exists public.ai_quota_config (
  tier        text primary key,
  daily_limit integer not null check (daily_limit >= -1),  -- -1 表示无限
  updated_at  timestamptz not null default now()
);

insert into public.ai_quota_config (tier, daily_limit) values
  ('guest',       20),
  ('free',        100),
  ('boh-ai-plus', 200),
  ('boh-pro',     -1),
  ('boh-max',     -1)
on conflict (tier) do nothing;

-- RLS: 仅管理员可写
alter table public.ai_quota_config enable row level security;

create policy "ai_quota_config_admin_all"
  on public.ai_quota_config
  for all
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());

create policy "ai_quota_config_read_all"
  on public.ai_quota_config
  for select
  using (true);
