-- Forum anti-spam hardening:
-- 1) tighten insert RLS so users can only write their own posts/comments
-- 2) enforce user-level post/comment rate limits in the database
-- 3) record blocked attempts for later moderation/admin review

begin;

alter table public.posts enable row level security;
alter table public.comments enable row level security;

-- Remove broad insert policies that only check "authenticated".
drop policy if exists "登录用户可以发布帖子" on public.posts;
drop policy if exists "Auth insert comment" on public.comments;

-- Keep/recreate owner-bound insert policies with stable names.
drop policy if exists posts_insert_own on public.posts;
create policy posts_insert_own on public.posts
  for insert to authenticated
  with check (auth.uid() = author_id);

drop policy if exists comments_insert_own on public.comments;
create policy comments_insert_own on public.comments
  for insert to authenticated
  with check (auth.uid() = author_id);

create table if not exists public.forum_rate_limit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  rule_code text not null,
  target_id uuid null,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_forum_rate_limit_events_user_created
  on public.forum_rate_limit_events (user_id, created_at desc);

alter table public.forum_rate_limit_events enable row level security;

drop policy if exists forum_rate_limit_events_admin_select on public.forum_rate_limit_events;
create policy forum_rate_limit_events_admin_select on public.forum_rate_limit_events
  for select to authenticated
  using (public.current_user_is_admin());

create or replace function public.log_forum_rate_limit_event(
  p_user_id uuid,
  p_target_type text,
  p_rule_code text,
  p_target_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.forum_rate_limit_events (user_id, target_type, rule_code, target_id)
  values (p_user_id, p_target_type, p_rule_code, p_target_id);
exception
  when others then
    -- Logging must never make the primary insert path fail with a different error.
    null;
end;
$$;

revoke all on function public.log_forum_rate_limit_event(uuid, text, text, uuid) from public;
grant execute on function public.log_forum_rate_limit_event(uuid, text, text, uuid) to authenticated;
grant execute on function public.log_forum_rate_limit_event(uuid, text, text, uuid) to service_role;

create or replace function public.enforce_forum_post_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:NOT_AUTHENTICATED:请先登录后再发布';
  end if;

  if new.author_id is distinct from v_user_id then
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:AUTHOR_MISMATCH:只能以当前登录账号发布内容';
  end if;

  if public.current_user_is_admin() then
    return new;
  end if;

  if exists (
    select 1
      from public.posts p
     where p.author_id = v_user_id
       and p.created_at >= now() - interval '30 seconds'
     limit 1
  ) then
    perform public.log_forum_rate_limit_event(v_user_id, 'post', 'POST_COOLDOWN', new.id);
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:POST_COOLDOWN:发布太频繁了，请 30 秒后再试';
  end if;

  if (
    select count(*)
      from public.posts p
     where p.author_id = v_user_id
       and p.created_at >= now() - interval '10 minutes'
  ) >= 5 then
    perform public.log_forum_rate_limit_event(v_user_id, 'post', 'POST_10M_LIMIT', new.id);
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:POST_10M_LIMIT:短时间内发布帖子较多，请稍后再试';
  end if;

  return new;
end;
$$;

create or replace function public.enforce_forum_comment_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:NOT_AUTHENTICATED:请先登录后再回复';
  end if;

  if new.author_id is distinct from v_user_id then
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:AUTHOR_MISMATCH:只能以当前登录账号回复';
  end if;

  if public.current_user_is_admin() then
    return new;
  end if;

  if exists (
    select 1
      from public.comments c
     where c.author_id = v_user_id
       and c.created_at >= now() - interval '10 seconds'
     limit 1
  ) then
    perform public.log_forum_rate_limit_event(v_user_id, 'comment', 'COMMENT_COOLDOWN', new.id);
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:COMMENT_COOLDOWN:回复太频繁了，请 10 秒后再试';
  end if;

  if (
    select count(*)
      from public.comments c
     where c.author_id = v_user_id
       and c.created_at >= now() - interval '10 minutes'
  ) >= 20 then
    perform public.log_forum_rate_limit_event(v_user_id, 'comment', 'COMMENT_10M_LIMIT', new.id);
    raise exception using
      errcode = 'P0001',
      message = 'FORUM_RATE_LIMIT:COMMENT_10M_LIMIT:短时间内回复较多，请稍后再试';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_forum_post_rate_limit() from public;
revoke all on function public.enforce_forum_comment_rate_limit() from public;

drop trigger if exists trg_forum_post_rate_limit on public.posts;
create trigger trg_forum_post_rate_limit
  before insert on public.posts
  for each row
  execute function public.enforce_forum_post_rate_limit();

drop trigger if exists trg_forum_comment_rate_limit on public.comments;
create trigger trg_forum_comment_rate_limit
  before insert on public.comments
  for each row
  execute function public.enforce_forum_comment_rate_limit();

commit;
