-- 论坛周签到：每周可签到一次，连续4周奖励5积分

create table if not exists public.forum_weekly_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  week_start_date date not null,
  signed_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now()
);

create unique index if not exists uq_forum_weekly_checkins_user_week
  on public.forum_weekly_checkins (user_id, week_start_date);

create index if not exists idx_forum_weekly_checkins_user_signed_at
  on public.forum_weekly_checkins (user_id, signed_at desc);

alter table public.forum_weekly_checkins enable row level security;

drop policy if exists forum_weekly_checkins_select_own on public.forum_weekly_checkins;
create policy forum_weekly_checkins_select_own
  on public.forum_weekly_checkins
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists forum_weekly_checkins_insert_own on public.forum_weekly_checkins;
create policy forum_weekly_checkins_insert_own
  on public.forum_weekly_checkins
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create or replace function public.get_weekly_checkin_status()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_now_local timestamp := timezone('Asia/Shanghai', now());
  v_current_week_start date := date_trunc('week', v_now_local)::date;
  v_target_week date;
  v_anchor_week date;
  v_has_signed boolean := false;
  v_streak integer := 0;
  v_next_reward integer := 4;
  v_current_points integer := 0;
begin
  if v_user_id is null then
    return jsonb_build_object(
      'ok', false,
      'message', 'NOT_AUTHENTICATED'
    );
  end if;

  select coalesce(points, 0)
    into v_current_points
    from public.profiles
   where id = v_user_id;

  select exists (
    select 1
      from public.forum_weekly_checkins
     where user_id = v_user_id
       and week_start_date = v_current_week_start
  ) into v_has_signed;

  if v_has_signed then
    v_anchor_week := v_current_week_start;
  else
    v_anchor_week := (v_current_week_start - interval '1 week')::date;
  end if;

  v_target_week := v_anchor_week;
  loop
    exit when not exists (
      select 1
        from public.forum_weekly_checkins
       where user_id = v_user_id
         and week_start_date = v_target_week
    );

    v_streak := v_streak + 1;
    v_target_week := (v_target_week - interval '1 week')::date;
  end loop;

  v_next_reward := 4 - mod(v_streak, 4);
  if v_next_reward = 0 then
    v_next_reward := 4;
  end if;

  return jsonb_build_object(
    'ok', true,
    'already_signed', v_has_signed,
    'has_signed_this_week', v_has_signed,
    'current_streak', v_streak,
    'points_awarded', 0,
    'current_points', v_current_points,
    'next_reward_in', v_next_reward,
    'current_week_start', v_current_week_start,
    'message', 'OK'
  );
end;
$$;

create or replace function public.submit_weekly_checkin()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_now_local timestamp := timezone('Asia/Shanghai', now());
  v_current_week_start date := date_trunc('week', v_now_local)::date;
  v_target_week date;
  v_streak integer := 0;
  v_next_reward integer := 4;
  v_points_awarded integer := 0;
  v_current_points integer := 0;
  v_inserted_rows integer := 0;
begin
  if v_user_id is null then
    return jsonb_build_object(
      'ok', false,
      'message', 'NOT_AUTHENTICATED'
    );
  end if;

  insert into public.forum_weekly_checkins (user_id, week_start_date, signed_at)
  values (v_user_id, v_current_week_start, now())
  on conflict (user_id, week_start_date) do nothing;

  get diagnostics v_inserted_rows = row_count;

  if v_inserted_rows = 0 then
    return public.get_weekly_checkin_status()
      || jsonb_build_object(
        'already_signed', true,
        'has_signed_this_week', true,
        'points_awarded', 0,
        'message', 'ALREADY_SIGNED_THIS_WEEK'
      );
  end if;

  v_target_week := v_current_week_start;
  loop
    exit when not exists (
      select 1
        from public.forum_weekly_checkins
       where user_id = v_user_id
         and week_start_date = v_target_week
    );

    v_streak := v_streak + 1;
    v_target_week := (v_target_week - interval '1 week')::date;
  end loop;

  if mod(v_streak, 4) = 0 then
    v_points_awarded := 5;

    update public.profiles
       set points = coalesce(points, 0) + v_points_awarded
     where id = v_user_id
     returning points into v_current_points;
  else
    select coalesce(points, 0)
      into v_current_points
      from public.profiles
     where id = v_user_id;
  end if;

  v_next_reward := 4 - mod(v_streak, 4);
  if v_next_reward = 0 then
    v_next_reward := 4;
  end if;

  return jsonb_build_object(
    'ok', true,
    'already_signed', false,
    'has_signed_this_week', true,
    'current_streak', v_streak,
    'points_awarded', v_points_awarded,
    'current_points', coalesce(v_current_points, 0),
    'next_reward_in', v_next_reward,
    'current_week_start', v_current_week_start,
    'message', 'CHECKIN_SUCCESS'
  );
end;
$$;

revoke all on function public.get_weekly_checkin_status() from public;
revoke all on function public.submit_weekly_checkin() from public;

grant execute on function public.get_weekly_checkin_status() to authenticated;
grant execute on function public.get_weekly_checkin_status() to service_role;
grant execute on function public.submit_weekly_checkin() to authenticated;
grant execute on function public.submit_weekly_checkin() to service_role;
